### ISSUE TITLE
Android版本

### ISSUE THREAD

**Issue by cnjsstong** [Hybrid-Force/cordova-plugin-lean-push#1]
感谢分享！
感觉现在iOS端已经初具规模了，近期有做Android端的打算吗？

**Comment by Hybrid-Force** [comment]
感谢关注。是的，最近正打算写一下插件的Android部分。

**Comment by cnjsstong** [comment]
@Hybrid-Force 我自己也在尝试写Android的部分，但是发现一个问题。LeanCloud在文档[ https://leancloud.cn/docs/android_guide.html#应用程序初始化 ] 中强调，需要在Application的onCreate()方法中调用AVOSCloud.initialize(AppId,AppKey)来初始化。目前我好像没有发现比较好的方法来在Cordova插件中实现这一点，不知你有没有什么好想法？

**Comment by Hybrid-Force** [comment]
有。我已经基本上写好了Android的部分，但是还没有push到Github上。
正如文档中说明的那样，LeanCloud SDK需要在Application的onCreate中来初始化。由于LeanCloud的API和Parse的用法几乎一模一样，所以我借鉴了Parse的Cordova插件的解决方法，具体方法可以在[这里](https://github.com/taivo/parse-push-plugin)找到。：）

**Comment by cnjsstong** [comment]
其实之前我也想到过这个方法，但是总感觉太侵入性了……anyway，谢啦！

**Comment by phyng** [comment]
感谢上面提供的链接，在里面找到了我需要的 getInstallationId() 方法 :smile:
