### ISSUE TITLE
如何在程序中接受推送到的数据

### ISSUE THREAD

**Issue by mlzxy** [Hybrid-Force/cordova-plugin-lean-push#4]
Push提供的接口只有`subscribe` 相关的函数， 好像并没有**接收推送通知**方面的API， 问一下该如何接受通知呢？

是不是可以用cordova监听这件事呢？ 这里有一个插件：http://ngcordova.com/docs/plugins/pushNotifications/

> 自己刚刚接触mobile开发， 什么都不知道呀😂

**Comment by Hybrid-Force** [comment]
这个插件目前只是简单的接收并且在通知栏显示通知，并没有向Webview发送接收到的推送的内容。

不过接收推送消息是可以做到的，请参考这个插件的 @cnjsstong2 的 fork :smile:  ：https://github.com/cnjsstong2/cordova-plugin-lean-push/blob/master/src/ios/AppDelegate%2BLeanPush.m#L150

**Comment by mlzxy** [comment]
好的！ 立刻去学

**Comment by mlzxy** [comment]
看完大概明白了， 今天晚上试一下，多谢您 XD

**Comment by mlzxy** [comment]
我fork这个repo啦， 并且实现了接受消息的功能呢 🐻 见这里： https://github.com/BenBBear/cordova-plugin-leanpush  😃

**Comment by Hybrid-Force** [comment]
哇，厉害，太棒了！不如以后把两个repo给merge起来一起写写好吧。

**Comment by mlzxy** [comment]
好！

**Comment by cnjsstong** [comment]
我也觉得。其实把API定义好大家一起写写比较好。
